CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(50) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(20) NOT NULL DEFAULT 'staff',
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Products (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  SKU NVARCHAR(30) NOT NULL UNIQUE,
  Name NVARCHAR(100) NOT NULL,
  Category NVARCHAR(50) NOT NULL,
  Quantity INT NOT NULL DEFAULT 0,
  ReorderLevel INT NOT NULL DEFAULT 5,
  UnitPrice DECIMAL(10,2) NOT NULL DEFAULT 0,
  UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);